package config

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"os"

	"gopkg.in/yaml.v3"
)

// ErrConfigNotFound is returned when metis.yaml does not exist.
var ErrConfigNotFound = errors.New("config file not found")

// MetisConfig holds infrastructure-level configuration (equivalent to WordPress's wp-config.php).
// Application-level settings are stored in the DB SystemConfig table.
type MetisConfig struct {
	DBDriver         string            `yaml:"db_driver"`
	DBDSN            string            `yaml:"db_dsn"`
	SecretKey        string            `yaml:"secret_key"`
	JWTSecret        string            `yaml:"jwt_secret"`
	LicenseKeySecret string            `yaml:"license_key_secret"`
	FalkorDB         *FalkorDBConfig   `yaml:"falkordb,omitempty"`
	ClickHouse       *ClickHouseConfig `yaml:"clickhouse,omitempty"`
}

// ClickHouseConfig holds ClickHouse connection settings (required for APM features).
type ClickHouseConfig struct {
	DSN string `yaml:"dsn"`
}

// FalkorDBConfig holds FalkorDB connection settings (only required for AI edition).
type FalkorDBConfig struct {
	Addr     string `yaml:"addr"`
	Password string `yaml:"password,omitempty"`
	Database int    `yaml:"database,omitempty"`
}

// Load reads and parses metis.yaml from the given path.
func Load(path string) (*MetisConfig, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, ErrConfigNotFound
		}
		return nil, fmt.Errorf("read config: %w", err)
	}
	var cfg MetisConfig
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parse config: %w", err)
	}
	return &cfg, nil
}

// Save writes the config to a YAML file with 0600 permissions.
func (c *MetisConfig) Save(path string) error {
	header := "# Metis Configuration — auto-generated by installer\n# Do not edit manually unless you know what you're doing.\n\n"
	data, err := yaml.Marshal(c)
	if err != nil {
		return fmt.Errorf("marshal config: %w", err)
	}
	return os.WriteFile(path, append([]byte(header), data...), 0600)
}

// DefaultSQLiteConfig returns a MetisConfig with SQLite defaults.
// Secret fields are empty — call GenerateSecrets() to fill them.
func DefaultSQLiteConfig() *MetisConfig {
	return &MetisConfig{
		DBDriver: "sqlite",
		DBDSN:    "metis.db?_pragma=foreign_keys(1)&_pragma=journal_mode(WAL)",
	}
}

// DefaultDevConfig returns a MetisConfig targeting the local docker-compose
// stack (support-files/dev/docker-compose.yml): PostgreSQL, ClickHouse, FalkorDB.
// Secret fields are empty — call GenerateSecrets() to fill them.
func DefaultDevConfig() *MetisConfig {
	return &MetisConfig{
		DBDriver: "postgres",
		DBDSN:    "host=localhost port=5432 user=postgres password=password dbname=postgres sslmode=disable",
		ClickHouse: &ClickHouseConfig{
			DSN: "clickhouse://default:@localhost:9000/otel",
		},
		FalkorDB: &FalkorDBConfig{
			Addr: "localhost:6379",
		},
	}
}

// GenerateSecrets fills jwt_secret and license_key_secret with
// cryptographically random 64-character hex strings.
func (c *MetisConfig) GenerateSecrets() error {
	b := make([]byte, 32)

	if _, err := rand.Read(b); err != nil {
		return fmt.Errorf("generate secret_key: %w", err)
	}
	c.SecretKey = hex.EncodeToString(b)

	if _, err := rand.Read(b); err != nil {
		return fmt.Errorf("generate jwt_secret: %w", err)
	}
	c.JWTSecret = hex.EncodeToString(b)

	if _, err := rand.Read(b); err != nil {
		return fmt.Errorf("generate license_key_secret: %w", err)
	}
	c.LicenseKeySecret = hex.EncodeToString(b)
	return nil
}
